# Appveyor script to build and deploy the Yadoms plugin-SDK for Windows

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Win32

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

init:
  - ps: Write-Host "`n### Build and deploy Yadoms plugin-SDK for Windows`n`n"
  

# Add pre-compiled dependencies in cache
cache:
  - extra_libs\boost_1_65_1 -> '.appveyor.yml'
  - extra_libs\poco-1.7.9-all -> '.appveyor.yml'
  - extra_libs\openssl -> '.appveyor.yml'
  - extra_libs\protobuf-3.4.1 -> '.appveyor.yml'
  - extra_libs\swig-3.0.12 -> '.appveyor.yml'

# scripts that run after cloning repository
install:
  # Download extra libs
  - ps: Write-Host "Download extra libs..."
  - ps: if (!(Test-Path 'extra_libs')) { mkdir 'extra_libs' }
  - ps: pushd extra_libs
  - ps: if (!(Test-Path 'boost_1_65_1')) { Invoke-WebRequest http://yadoms.com/appveyor_build/boost_1_65_1-build.7z -OutFile boost.7z; 7z x boost.7z -bso0 }
  - ps: if (!(Test-Path 'poco-1.7.9-all')) { Invoke-WebRequest http://yadoms.com/appveyor_build/poco-1.7.9-all-build.7z -OutFile poco.7z; 7z x poco.7z -bso0 }
  - ps: if (!(Test-Path 'openssl')) { Invoke-WebRequest http://yadoms.com/appveyor_build/openssl-build.7z -OutFile openssl.7z; 7z x openssl.7z -bso0 }
  - ps: if (!(Test-Path 'swig-3.0.12')) { Invoke-WebRequest http://yadoms.com/appveyor_build/swig-3.0.12-build.7z -OutFile swig.7z; 7z x swig.7z -bso0 }
  - ps: if (!(Test-Path 'protobuf-3.4.1')) { Invoke-WebRequest http://yadoms.com/appveyor_build/protobuf-3.4.1-build.7z -OutFile protobuf.7z; 7z x protobuf.7z -bso0 }
  - ps: rm *.7z
  - ps: popd    
  - ps: Write-Host "[END] install"

# scripts to run before build
before_build:
  # CMAKE 3.9.4
  - ps: choco upgrade cmake.install --installargs 'ADD_CMAKE_TO_PATH=""System""'
  - ps: $env:Path += ";C:\Program Files\CMake\bin"
  - ps: refreshenv
  - ps: cmake --version

  # Yadoms sources
  - ps: Write-Host "Downloading yadoms sources from $env:buildBranch branch..."
  - cmd: git clone -q --depth=1 --branch=%buildBranch% git://github.com/Yadoms/yadoms.git
  
  # Read current Yadoms version
  - ps: $yadomsVersion = (Select-String -Pattern 'YadomsVersion\("(.*)"\)' -path .\yadoms\sources\server\Version.h).Matches.Groups[1].Value
  - ps: Write-Host "Yadoms version is $yadomsVersion"

  # Yadoms configuration file
  - ps: Write-Host "Create Yadoms configuration file CMakeListsUserConfig.txt..."
  - ps: $cd_for_cmake="$pwd".Replace("\", "/")
  - ps: Write-Host $cd_for_cmake
  - ps: Set-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(BOOST_ROOT "' + $cd_for_cmake + '/extra_libs/boost_1_65_1")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(POCO_ROOT "' + $cd_for_cmake + '/extra_libs/poco-1.7.9-all")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(OPENSSL_ROOT "' + $cd_for_cmake + '/extra_libs/openssl")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PROTOBUF_ROOT "' + $cd_for_cmake + '/extra_libs/protobuf-3.4.1")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(SWIG_ROOT "' + $cd_for_cmake + '/extra_libs/swig-3.0.12")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PYTHON_ROOT "C:/Python27")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(COTIRE_USE ON)')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(COTIRE_USE_UNITY ON)')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PYTHON_USE_SOURCES OFF)')
  - ps: cat 'yadoms/sources/CMakeListsUserConfig.txt'
  
  # Create solution
  - ps: pushd yadoms
  - cmd: cmake_windows.cmd v141_xp
  - ps: popd
  
build: off
  # Use custom build
  
build_script:
  # Build Yadoms
  - ps: pushd yadoms/projects
  - ps: Write-Host 'Build...'
  - ps: msbuild shared/all_unity.vcxproj /p:Configuration=$env:configuration /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: Write-Host 'Finalize output...'
  - ps: cp ../config/yadoms.ini ../builds/$env:configuration/
  - ps: popd

  # Copy all files to generate SDK package
  - ps: Write-Host 'Copy all files to generate SDK package...'
  - ps: $yadomsRoot = ".\yadoms"
  - ps: $boostRoot = ".\extra_libs\boost_1_65_1"
  - ps: $pocoRoot = ".\extra_libs\poco-1.7.9-all"
  - ps: $out=".\SDK"
  - ps: $robocopyFlags="/MT","/np","/njh","/njs","/ns","/nc"
  # Clean
  - ps: Write-Host "Clean $out folder..."
  - ps: Remove-Item $out -Force -Recurse -ErrorAction SilentlyContinue
  # Copy Boost
  - ps: Write-Host "Copy Boost folder..."
  - ps: robocopy "$boostRoot\boost" "$out\libs\boost\boost" $robocopyFlags /e
  - ps: robocopy "$boostRoot\stage" "$out\libs\boost\stage" $robocopyFlags /e
  # Copy Poco
  - ps: Write-Host "Copy Poco folder..."
  - ps: robocopy "$pocoRoot\lib" "$out\libs\poco\lib" $robocopyFlags /e
  - ps: robocopy "$pocoRoot" "$out\libs\poco" "VERSION" $robocopyFlags
  - ps: robocopy "$pocoRoot\Util\src" "$out\libs\poco\Util\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Util\include" "$out\libs\poco\Util\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\NetSSL_OpenSSL\src" "$out\libs\poco\NetSSL_OpenSSL\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\NetSSL_OpenSSL\include" "$out\libs\poco\NetSSL_OpenSSL\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Crypto\src" "$out\libs\poco\Crypto\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Crypto\include" "$out\libs\poco\Crypto\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Zip\src" "$out\libs\poco\Zip\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Zip\include" "$out\libs\poco\Zip\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\XML\src" "$out\libs\poco\XML\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\XML\include" "$out\libs\poco\XML\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Net\src" "$out\libs\poco\Net\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Net\include" "$out\libs\poco\Net\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\JSON\src" "$out\libs\poco\JSON\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\JSON\include" "$out\libs\poco\JSON\include" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Foundation\src" "$out\libs\poco\Foundation\src" $robocopyFlags /e
  - ps: robocopy "$pocoRoot\Foundation\include" "$out\libs\poco\Foundation\include" $robocopyFlags /e
  # Copy Yadoms
  - ps: Write-Host "Copy Yadoms folder..."
  - ps: robocopy "$yadomsRoot\sources" "$out\yadoms\sources" $robocopyFlags /e /xd "plugins"
  - ps: robocopy "$yadomsRoot\sources\plugins" "$out\yadoms\sources\plugins" $robocopyFlags 
  - ps: robocopy "$yadomsRoot\sources\plugins\common" "$out\yadoms\sources\plugins\common" $robocopyFlags /e
  - ps: robocopy "$yadomsRoot\sources\plugins\dev-EmptyPlugin" "$out\yadoms\sources\plugins\dev-EmptyPlugin" $robocopyFlags /e
  - ps: robocopy "$yadomsRoot\sources\plugins\dev-FakePlugin" "$out\yadoms\sources\plugins\dev-FakePlugin" $robocopyFlags /e
  - ps: robocopy "$yadomsRoot\licensing" "$out\yadoms\licensing" $robocopyFlags /e
  - ps: robocopy "$yadomsRoot\psd" "$out\yadoms\psd" $robocopyFlags /e
  - ps: robocopy "$yadomsRoot\builds\DEBUG" "$out\yadoms\builds\DEBUG" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\builds\RELEASE" "$out\yadoms\builds\RELEASE" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\shared\DEBUG" "$out\yadoms\projects\shared\DEBUG" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\shared\RELEASE" "$out\yadoms\projects\shared\RELEASE" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\plugin_cpp_api\DEBUG" "$out\yadoms\projects\plugin_cpp_api\DEBUG" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\plugin_cpp_api\RELEASE" "$out\yadoms\projects\plugin_cpp_api\RELEASE" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\plugin_IPC\DEBUG" "$out\yadoms\projects\plugin_IPC\DEBUG" $robocopyFlags /e /xf "*.ilk"
  - ps: robocopy "$yadomsRoot\projects\plugin_IPC\RELEASE" "$out\yadoms\projects\plugin_IPC\RELEASE" $robocopyFlags /e /xf "*.ilk"

  # Create the SDK package
  - ps: Write-Host 'Create the SDK package...'
  - ps: $yadomsGitdate = git --git-dir=.\yadoms\.git log -1 --format=%cI 
  - ps: Write-Host "Generating SDK package for Yadoms " + $yadomsVersion + " released on " + $yadomsGitdate
  - ps: 7z a -tzip plugin-SDK-windows-$yadomsVersion.zip $out
  
# after_build: TODO ménage ?
  # # Needed step to remove directory structure of artifacts
  # - ps: |
     # $packageFile = Get-ChildItem "yadoms/builds/package" -Name -Filter *.exe
     # Push-AppveyorArtifact yadoms/builds/package/$packageFile -FileName $packageFile -DeploymentName 'Yadoms installer'
     # $packageFile = Get-ChildItem "yadoms/builds/package" -Name -Filter *.zip
     # Push-AppveyorArtifact yadoms/builds/package/$packageFile -FileName $packageFile -DeploymentName 'Yadoms portable'
     # $packageFile = Get-ChildItem "." -Name -Filter *.zip
     # Push-AppveyorArtifact $packageFile -FileName $packageFile -DeploymentName 'Yadoms Update package'

artifacts:
  - path: plugin-SDK-windows-*.zip
    name: 'Yadoms plugin SDK for Windows'
    
deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.jano42.fr
    username: janofnxr-yadoms
    password:
      secure: 8tosT9FAJxX+SRgkw02I1A==
    folder: appveyor_build/win32
    debug: true     # show complete FTP log TODO virer
