# Appveyor script to build and deploy the Yadoms plugin-SDK for Windows

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Win32

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

init:
  - ps: Write-Host "`n### Build and deploy Yadoms plugin-SDK for Windows`n`n"
  

# Add pre-compiled dependencies in cache
# cache:
  # - extra_libs\boost_1_65_1 -> '.appveyor.yml'
  # - extra_libs\poco-1.7.9-all -> '.appveyor.yml'
  # - extra_libs\openssl -> '.appveyor.yml'
  # - extra_libs\protobuf-3.4.1 -> '.appveyor.yml'
  # - extra_libs\swig-3.0.12 -> '.appveyor.yml'
  # - extra_libs\cmake-3.10.2 -> '.appveyor.yml'

# scripts that run after cloning repository
install:
  # Download extra libs
  - ps: Write-Host "Download extra libs..."
  - ps: if (!(Test-Path 'extra_libs')) { mkdir 'extra_libs' }
  - ps: pushd extra_libs
  - ps: if (!(Test-Path 'boost_1_65_1')) { Invoke-WebRequest http://yadoms.com/appveyor_build/boost_1_65_1-build.7z -OutFile boost.7z; 7z x boost.7z -bso0 }
  - ps: if (!(Test-Path 'poco-1.7.9-all')) { Invoke-WebRequest http://yadoms.com/appveyor_build/poco-1.7.9-all-build.7z -OutFile poco.7z; 7z x poco.7z -bso0 }
  - ps: if (!(Test-Path 'openssl')) { Invoke-WebRequest http://yadoms.com/appveyor_build/openssl-build.7z -OutFile openssl.7z; 7z x openssl.7z -bso0 }
  - ps: if (!(Test-Path 'swig-3.0.12')) { Invoke-WebRequest http://yadoms.com/appveyor_build/swig-3.0.12-build.7z -OutFile swig.7z; 7z x swig.7z -bso0 }
  - ps: if (!(Test-Path 'protobuf-3.4.1')) { Invoke-WebRequest http://yadoms.com/appveyor_build/protobuf-3.4.1-build.7z -OutFile protobuf.7z; 7z x protobuf.7z -bso0 }
  - ps: if (!(Test-Path 'cmake-3.10.2')) { Invoke-WebRequest https://cmake.org/files/v3.10/cmake-3.10.2.zip -OutFile cmake.7z; 7z x cmake.7z -bso0 }
  - ps: rm *.7z
  - ps: popd    
  - ps: Write-Host "[END] install"

# scripts to run before build
before_build:
  # Yadoms sources
  - ps: Write-Host "Downloading yadoms sources from $env:buildBranch branch..."
  - cmd: git clone -q --depth=1 --branch=%buildBranch% git://github.com/Yadoms/yadoms.git
  
  # Read current Yadoms version
  - ps: $yadomsVersion = (Select-String -Path yadoms\sources\server\changelog.md -Pattern '^### (.*)$')[0] | Foreach-Object {$_.Matches} | Foreach-Object {$_.Groups[1].Value}
  - ps: Write-Host "Yadoms version is $yadomsVersion"

  # Yadoms configuration file
  - ps: Write-Host "Create Yadoms configuration file CMakeListsUserConfig.txt..."
  - ps: $cd_for_cmake="$pwd".Replace("\", "/")
  - ps: Write-Host $cd_for_cmake
  - ps: Set-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(ALTERNATIVE_CMAKE_ROOT "/extra_libs/cmake-3.10.2")')
  - ps: Set-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(BOOST_ROOT "' + $cd_for_cmake + '/extra_libs/boost_1_65_1")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(POCO_ROOT "' + $cd_for_cmake + '/extra_libs/poco-1.7.9-all")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(OPENSSL_ROOT "' + $cd_for_cmake + '/extra_libs/openssl")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PROTOBUF_ROOT "' + $cd_for_cmake + '/extra_libs/protobuf-3.4.1")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(SWIG_ROOT "' + $cd_for_cmake + '/extra_libs/swig-3.0.12")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PYTHON_ROOT "C:/Python27")')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(COTIRE_USE ON)')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(COTIRE_USE_UNITY ON)')
  - ps: Add-Content 'yadoms/sources/CMakeListsUserConfig.txt' ('set(PYTHON_USE_SOURCES OFF)')
  - ps: cat 'yadoms/sources/CMakeListsUserConfig.txt'

  # Patch plugins list to build only wanted plugins
  - ps: Write-Host "Patch plugins list to build only wanted plugins..."
  - ps: Remove-Item 'yadoms/sources/plugins/CMakeLists.txt'
  - ps: Set-Content 'yadoms/sources/plugins/CMakeLists.txt' ('add_subdirectory(dev-EmptyPlugin)')
  - ps: Set-Content 'yadoms/sources/plugins/CMakeLists.txt' ('add_subdirectory(dev-FakePlugin)')
  - ps: Set-Content 'yadoms/sources/plugins/CMakeLists.txt' ('set(PLUGINLIST dev-EmptyPlugin dev-FakePlugin PARENT_SCOPE)')
  
  # Create solution
  - ps: pushd yadoms
  - cmd: cmake_windows.cmd v141_xp
  - ps: popd
  
build: off
  # Use custom build
  
build_script:
  # Build Yadoms
  - ps: pushd yadoms/projects
  - ps: Write-Host 'Build...'
  - ps: msbuild shared/all_unity.vcxproj /p:Configuration=Debug /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild shared/all_unity.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: Write-Host 'Finalize output...'
  - ps: cp ../config/yadoms.ini ../builds/DEBUG/
  - ps: cp ../config/yadoms.ini ../builds/RELEASE/
  - ps: popd

  # Copy all files to generate SDK package
  - ps: Write-Host 'Copy all files to generate SDK package...'
  - ps: $sdkOut=".\SDK"
  # Clean
  - ps: Write-Host "Clean $sdkOut folder..."
  - ps: if (Test-Path -Path $sdkOut) { Remove-Item $sdkOut -Force -Recurse -ErrorAction SilentlyContinue }
  # Copy
  - ps: .\moveSDKResources.ps1

  # Create the SDK package
  - ps: Write-Host 'Create the SDK package...'
  - ps: $yadomsGitdate = git --git-dir=.\yadoms\.git log -1 --format=%cI 
  - ps: Write-Host "Generating SDK package for Yadoms " + $yadomsVersion + " released on " + $yadomsGitdate
  - ps: 7z a -tzip plugin-SDK-windows-$yadomsVersion.zip $sdkOut
  
artifacts:
  - path: plugin-SDK-windows-*.zip
    name: 'Yadoms plugin SDK for Windows'
    
deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.jano42.fr
    username: janofnxr-yadoms
    password:
      secure: 8tosT9FAJxX+SRgkw02I1A==
    folder: appveyor_build/win32
